# junwei's .bashrc append 

# User specific aliases and functions
#junwei tools

#alibaba commands
alias lvsproxy='ssh linggao@10.65.251.64'


#6Wind make commands
xuser=`whoami`
if [ X"$xuser" == "Xjunwei" ] ; then
alias apollo='ssh -X h_debit@apollo';
alias artemis='ssh -X h_debit@artemis';
alias pandora='ssh -X h_debit@pandora';
alias shanghai='ssh -X h_debit@shanghai';
alias tianjin='ssh -X h_debit@tianjin';
alias avatar='ssh avatar';
alias wukong='ssh -X h_debit@wukong';
alias bajie='ssh -X h_debit@bajie';
alias caviumhost1='ssh -X h_debit@caviumhost1';
alias caviumhost2='ssh -X h_debit@caviumhost2';
alias stand='ssh -X h_debit@stand';
alias alone='ssh -X h_debit@alone';
alias lion='ssh -X h_debit@lion';
alias tiger='ssh -X h_debit@tiger';
alias tamarillo='ssh -X h_debit@tamarillo';
alias pepino='ssh -X h_debit@pepino';
alias puma='ssh -X h_debit@puma';
alias demonicus='ssh -X h_debit@demonicus';
alias willow='ssh -X h_debit@willow';
alias poplar='ssh -X h_debit@poplar';
alias oak='ssh -X h_debit@oak';
alias larch='ssh -X h_debit@larch';
alias cedar='ssh -X h_debit@cedar';
alias sequoia='ssh -X h_debit@sequoia';
alias glacon='ssh -X h_debit@glacon';
alias palm='ssh -X h_debit@palm';
alias yeti='ssh -X h_debit@yeti';
alias lucky='ssh -X h_debit@lucky';
alias cobra3='ssh -X h_debit@cobra3';
alias cobra='ssh -X h_debit@cobra';
alias cobra2='ssh -X h_debit@cobra2';
alias benjamin='ssh -X h_debit@benjamin';
alias baobab='ssh -X h_debit@baobab';
alias quake='ssh -X h_debit@quake';
alias ken='ssh -X h_debit@ken';
alias agaric='ssh -X h_debit@agaric';
alias junweiagaric='ssh junwei@agaric';
#targets
alias lasa='ssh -X h_debit@shanghai -t tip lasa'
alias xian='ssh -X h_debit@shanghai -t tip xian'

alias taibei='ssh -X h_debit@tianjin -t tip taibei'
alias aomen='ssh -X h_debit@tianjin -t tip aomen'

alias green='ssh -X h_debit@tianjin -t tip green'
alias yellow='ssh -X h_debit@tianjin -t tip yellow'

alias toyota='ssh -X h_debit@artemis -t tip toyota'
alias honda='ssh -X h_debit@artemis -t tip honda'


alias watermeloon='ssh -X h_debit@wukong -t tip watermelon'
alias coconut='ssh -X h_debit@wukong -t tip coconut'

alias grape='ssh -X h_debit@wukong -t tip grape'
alias test='ssh -X h_debit@bajie -t tip test'
alias slime='ssh root@10.81.0.193 -t cu -l /dev/ttyS4a'

#XLP
alias bronson='ssh -X h_debit@willow -t tip bronson'
alias simone='ssh cobra -lh_debit -t bin/tip.sh simone'
alias yves='ssh -X h_debit@cobra -t bin/tip.sh yves'
alias robinson='ssh -X h_debit@willow -t tip robinson'
alias autobench_tiger='ssh -p5022 -X h_debit@tiger'

#pp81:
alias tequila='ssh root@10.81.0.181 -t cu -l /dev/ttyS2a'
alias paf='ssh root@10.81.0.181 -t cu -l /dev/ttyS4a'
alias kfar='ssh root@10.81.0.175 -t cu -l /dev/ttyS2a'
alias blat='ssh root@10.81.0.175 -t cu -l /dev/ttyS4a'
alias thym='ssh root@10.81.0.64 -t cu -l /dev/ttyS2a'
alias lavande='ssh root@10.81.0.64 -t cu -l /dev/ttyS4a'

alias grep='grep --color '

#log as junwei
alias junweilion='ssh lion' 
alias junweitiger='ssh tiger' 
alias junweipuma='ssh puma' 
alias junweilucky='ssh lucky' 

#pr list
alias prlist='ssh lion /home/junwei/script/pr.py'
alias checkpatch='/home/junwei/git/linux-generic-2.6.34/scripts/checkpatch.pl'

#grep exclude tags.
alias grep='grep --color --exclude tags'

else
#6WIND_HOME
alias 6WIND='ssh -1  root@222.128.2.191  -L 4000:10.80.2.243:4000 -L 5999:10.80.2.243:22 -L 5900:10.80.2.243:5900 -X'
alias junwei6WIND='ssh -X -p 5999 junwei@127.0.0.1'
fi;

##Virtualbox testbed
#function vtestbed() {
#	if [ "$1X" == "startX" ] ; then
#		VBoxManage startvm  HOST1 --type headless && sleep 5;
#		VBoxManage startvm  HOST2 --type headless;
#		VBoxManage startvm  VLeft --type headless;
#		VBoxManage startvm  VRight --type headless;
#	elif [ "$1X" == "stopX" ] ; then
#		VBoxManage controlvm VLeft poweroff;
#		VBoxManage controlvm VRight poweroff;
#		VBoxManage controlvm HOST2 acpipowerbutton;
#		VBoxManage controlvm HOST1 acpipowerbutton && sleep 5;
#	fi
#	echo "RUNNING VMS ..."
#	VBoxManage list runningvms
#}
#
#alias vhost1='ssh junwei@10.80.2.71 -X'
#alias vhost2='ssh junwei@10.80.2.74 -X'
#alias vleft='ssh junwei@10.80.2.71 -X -t minicom left'
#alias vright='ssh junwei@10.80.2.71 -X -t minicom right'
